#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import numpy as np
import matplotlib.pyplot as plt
import os
import time


class Main():

    def __init__(self):
        print("Main")

    def run(self):
        print("doing stuff...")
        graph = Graphics()
        plane_wave = PlaneWave()

        graph.heat_map(my_wave, title='Real part')
        #graph.contour(plane_wave, title='Real part')


#####################
class Wave():

    def __init__(self, length, delta):
        print("new wave created")
        self.X, self.Y = self.get_xy_series(length,delta)
        #self.Z = self.create_z_series(length, delta)


    def get_xy_series(self, length, delta):
        x = np.linspace(-length, length, delta)
        y = x
        return np.meshgrid(x, y)

    def create_z_series(self, length, delta):
        print("not yet implemented in super-class")
        # put code here .... loopy stuff... infinite summmation
        return None

    def get_X(self):
        return self.X

    def get_Y(self):
        return self.Y

    def get_Z(self):
        return self.Z

#####################
#   For every new wave function, I´ll need to create a class that contains it
class PlaneWave(Wave):
    def __init__(self, length=10 , delta=100):
        print("my wave created")
        super(PlaneWave, self).__init__(length, delta)
        self.Z = self.phi()

    def phi(self):
        '''
        When plotting, python defaults to the real part.
        '''
        return np.exp(1j*(self.get_X() + self.get_Y()))

    def phi_real(self):
        #   how can I define the title at this point?
        return (self.phi()).real

    def phi_imag(self):
        return (self.phi()).imag
#####################
class Graphics():
    def __init__(self):
        print("graphics object created")

    def contour(self, wave, title="Title", xlabel='x', ylabel='y'):
        plot = plt.contour(wave.get_Z())
        plt.title(title)
        plt.ylabel(xlabel)
        plt.xlabel(ylabel)
        plt.colorbar(plot)
        plt.show()

    def heat_map(self, wave, title="Title", xlabel='x', ylabel='y'):
        plot = plt.imshow(wave.get_Z())
        plt.title(title)
        plt.ylabel(xlabel)
        plt.xlabel(ylabel)
        plt.colorbar(plot)
        plt.show()



########### Script

main = Main()
main.run()